### PR TITLE
storybook updated

### PR DESCRIPTION
**Pull request by prvn-mhsh**
image
image
image

### CODE REVIEW

**Comment by ramsunvtech** [comment]
LGTM. add further screenshot for 

UserNameInput, UserStackList, UseFacepile, Switch, SimpleTable

**Comment by ramsunvtech** [comment]
@prvn-mhsh, try to keep better title instead of "storybook updated" thanks

**Comment by prvn-mhsh** [comment]
image

**Comment by prvn-mhsh** [comment]
image
image
image

**Pull request merged**
