### PR TITLE
feat: add copy button component

### PR DESCRIPTION
**Pull request by sriramanvellingiri**

### CODE REVIEW

**Comment by ramsunvtech** [comment]
Can add demo screencast

**Comment by sriramanvellingiri** [comment]
@ramsunvtech  added the demo cast
https://github.com/web-slate/TwixtUI/assets/11173747/ff107096-5d43-453b-a0bd-dadc291abcf2

**Comment by sriramanvellingiri** [comment]
@ramsunvtech story book doc

image

**Comment by ramsunvtech** [comment]
LGTM, next time, update screenshot it in PR Description

**Pull request merged**
